version: '3.8'
services:
  db:
    container_name: ${MYSQL_NAME}
    ports:
      - "${MYSQL_PORT}:3306"
    image: ${MYSQL_IMAGE}
    volumes:
      - ${MYSQL_VOLUMES}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}


  wordpress:
    container_name: ${WORDPRESS_NAME}
    depends_on:
      - db
    image: ${WORDPRESS_DB_IMAGE}
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ${WORDPRESS_DB_VOLUMES}:/var/www/html



